### ISSUE TITLE
Create custom error page

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/SkyPulse#5]
Please create a custom error page, starting with the current coming soon page as a template.  Keep that layout, but just change the route, text, and contents.  Alternatively, you can create a custom or creative page.

Requirements
- Create a custom error page
- Place the page at /pages/404.js

**Comment by ManavJoshi111** [comment]
@brandonbyr4 I want to work on this issue, do you have any designs in your mind?

**Comment by brandonbyr4** [comment]
@ManavJoshi111 thanks, I've assigned this issue to you.  You can follow the design on the /coming-soon.js page as a starting point, or feel free to customize it. ![image](https://i.ibb.co/LhCVQD7/Capture.png)
